name: Check Python Version

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  check-python-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check Python version
      run: python --version
