name: Snyk Scanning to defect dojo

on:
  workflow_dispatch:
  
jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Checkout external repository
      uses: actions/checkout@v2
        
    - name: Run Python Script with Arguments
      run: |
        git clone https://github.com/4nYuj1n/snyk_scanner.git
        pip install -r snyk_scanner/requirements.txt
        python3 snyk_scanner/snyk_scan.py -k ${{ secrets.SNYK_API_TOKEN }} -u https://a1a4-124-158-150-186.ngrok-free.app -f .. -p custody.depository.id
